version: '2'

services:
  nodejs:
    container_name: nodejs
    entrypoint: "/bin/sh ./docker-entrypoint-prod.sh"
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - .:/application
    environment:
      - CHOKIDAR_USEPOLLING=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wallet.rule=Host(`wallet.chylo.pl`)"
      - "traefik.http.routers.wallet.entrypoints=web"
    networks:
      proxy:
        ipv4_address: 10.200.0.4

networks:
  proxy:
    external: true
