version: '3'

services:
  nodejs:
    container_name: nodejs
    entrypoint: "/bin/sh ./docker-entrypoint.sh"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/application
    environment:
      - CHOKIDAR_USEPOLLING=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wallet.rule=Host(`wallet.chylo.local`)"
      - "traefik.http.routers.wallet.entrypoints=web"
    networks:
      proxy:
        ipv4_address: 10.200.0.4

networks:
  proxy:
    external: true
